import esbuild from 'esbuild';
import process from 'process';
import fs from 'fs';

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
    entryPoints: ['src/main.js'],
    bundle: true,
    external: ['obsidian'],
    format: 'cjs',
    target: 'es2018',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: prod,
    banner: {
        js: `/*
 * Recycle Bin - An Obsidian Plugin
 * https://github.com/wronginput/obsidian-recycle-bin
 * 
 * Translations generated by AI - corrections welcome!
 * Licensed under MIT
 */`
    }
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
